spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    name: test
    username: root
    password: root





# 指定全局配置文件
mybatis-plus:
  #config-location: classpath:mybatis-config.xml
  # 指定mapper.xml文件
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

